/**
 * Imágenes demo por ejercicio (Task 33) — generadas por
 * scripts/fetch-exercise-images.ts, NO editar a mano: re-correr el script.
 *
 * Origen: free-exercise-db (https://github.com/yuhonas/free-exercise-db),
 * licencia Unlicense (dominio público). Descargadas, reescaladas a 640px
 * (sharp, JPEG q72) y servidas localmente desde /public/images/ejercicios/db.
 *
 * Consumido por la biblioteca (#/ejercicios): si el ejercicio no está en este
 * mapa se cae a la portada del grupo (GROUP_IMAGES en biblioteca-view).
 */

export const EXERCISE_IMAGES: Record<string, string> = {
  "aduccion-cadera": "/images/ejercicios/db/aduccion-cadera.jpg",
  "apertura-inversa-banda": "/images/ejercicios/db/apertura-inversa-banda.jpg",
  "apertura-inversa-maquina": "/images/ejercicios/db/apertura-inversa-maquina.jpg",
  "apertura-inversa-polea": "/images/ejercicios/db/apertura-inversa-polea.jpg",
  "aperturas-mancuernas": "/images/ejercicios/db/aperturas-mancuernas.jpg",
  "aperturas-maquina": "/images/ejercicios/db/aperturas-maquina.jpg",
  "aperturas-polea": "/images/ejercicios/db/aperturas-polea.jpg",
  "arranque-barra": "/images/ejercicios/db/arranque-barra.jpg",
  "buenos-dias": "/images/ejercicios/db/buenos-dias.jpg",
  "clean-barra": "/images/ejercicios/db/clean-barra.jpg",
  "clean-mancuernas": "/images/ejercicios/db/clean-mancuernas.jpg",
  "clean-press-kettlebell": "/images/ejercicios/db/clean-press-kettlebell.jpg",
  "crunch": "/images/ejercicios/db/crunch.jpg",
  "crunch-invertido": "/images/ejercicios/db/crunch-invertido.jpg",
  "crunch-maquina": "/images/ejercicios/db/crunch-maquina.jpg",
  "crunch-oblicuo": "/images/ejercicios/db/crunch-oblicuo.jpg",
  "crunch-polea": "/images/ejercicios/db/crunch-polea.jpg",
  "cruzamiento-poleas": "/images/ejercicios/db/cruzamiento-poleas.jpg",
  "curl-arana": "/images/ejercicios/db/curl-arana.jpg",
  "curl-arrastrado": "/images/ejercicios/db/curl-arrastrado.jpg",
  "curl-barra": "/images/ejercicios/db/curl-barra.jpg",
  "curl-barra-z": "/images/ejercicios/db/curl-barra-z.jpg",
  "curl-femoral-sentado": "/images/ejercicios/db/curl-femoral-sentado.jpg",
  "curl-femoral-tumbado": "/images/ejercicios/db/curl-femoral-tumbado.jpg",
  "curl-inclinado": "/images/ejercicios/db/curl-inclinado.jpg",
  "curl-mancuernas": "/images/ejercicios/db/curl-mancuernas.jpg",
  "curl-martillo": "/images/ejercicios/db/curl-martillo.jpg",
  "curl-martillo-polea": "/images/ejercicios/db/curl-martillo-polea.jpg",
  "curl-muneca": "/images/ejercicios/db/curl-muneca.jpg",
  "curl-polea": "/images/ejercicios/db/curl-polea.jpg",
  "curl-predicador": "/images/ejercicios/db/curl-predicador.jpg",
  "curl-scott-barra": "/images/ejercicios/db/curl-scott-barra.jpg",
  "curl-zottman": "/images/ejercicios/db/curl-zottman.jpg",
  "dead-bug": "/images/ejercicios/db/dead-bug.jpg",
  "dominadas": "/images/ejercicios/db/dominadas.jpg",
  "dominadas-asistidas-banda": "/images/ejercicios/db/dominadas-asistidas-banda.jpg",
  "dominadas-supinas": "/images/ejercicios/db/dominadas-supinas.jpg",
  "elevacion-lateral-polea": "/images/ejercicios/db/elevacion-lateral-polea.jpg",
  "elevacion-piernas-colgado": "/images/ejercicios/db/elevacion-piernas-colgado.jpg",
  "elevacion-piernas-paralelas": "/images/ejercicios/db/elevacion-piernas-paralelas.jpg",
  "elevacion-piernas-tumbado": "/images/ejercicios/db/elevacion-piernas-tumbado.jpg",
  "elevacion-rodillas-colgado": "/images/ejercicios/db/elevacion-rodillas-colgado.jpg",
  "elevaciones-frontales": "/images/ejercicios/db/elevaciones-frontales.jpg",
  "elevaciones-laterales": "/images/ejercicios/db/elevaciones-laterales.jpg",
  "encogimiento-barra": "/images/ejercicios/db/encogimiento-barra.jpg",
  "encogimiento-trapecio": "/images/ejercicios/db/encogimiento-trapecio.jpg",
  "envion": "/images/ejercicios/db/envion.jpg",
  "extension-cuadriceps": "/images/ejercicios/db/extension-cuadriceps.jpg",
  "extension-muneca": "/images/ejercicios/db/extension-muneca.jpg",
  "extension-triceps-cuerda": "/images/ejercicios/db/extension-triceps-cuerda.jpg",
  "extension-triceps-maquina": "/images/ejercicios/db/extension-triceps-maquina.jpg",
  "extension-triceps-polea": "/images/ejercicios/db/extension-triceps-polea.jpg",
  "extension-triceps-sobrecabeza": "/images/ejercicios/db/extension-triceps-sobrecabeza.jpg",
  "face-pull": "/images/ejercicios/db/face-pull.jpg",
  "farmer-walk": "/images/ejercicios/db/farmer-walk.jpg",
  "flexion-lateral-tronco": "/images/ejercicios/db/flexion-lateral-tronco.jpg",
  "flexiones": "/images/ejercicios/db/flexiones.jpg",
  "flexiones-declinadas": "/images/ejercicios/db/flexiones-declinadas.jpg",
  "flexiones-diamante": "/images/ejercicios/db/flexiones-diamante.jpg",
  "flexiones-inclinadas": "/images/ejercicios/db/flexiones-inclinadas.jpg",
  "flexiones-palmada": "/images/ejercicios/db/flexiones-palmada.jpg",
  "fondos-banco": "/images/ejercicios/db/fondos-banco.jpg",
  "fondos-paralelas": "/images/ejercicios/db/fondos-paralelas.jpg",
  "gemelos-pie": "/images/ejercicios/db/gemelos-pie.jpg",
  "gemelos-prensa": "/images/ejercicios/db/gemelos-prensa.jpg",
  "gemelos-sentado": "/images/ejercicios/db/gemelos-sentado.jpg",
  "hip-thrust": "/images/ejercicios/db/hip-thrust.jpg",
  "hiperextensiones": "/images/ejercicios/db/hiperextensiones.jpg",
  "jalon-agarre-neutro": "/images/ejercicios/db/jalon-agarre-neutro.jpg",
  "jalon-polea": "/images/ejercicios/db/jalon-polea.jpg",
  "jalon-polea-unilateral": "/images/ejercicios/db/jalon-polea-unilateral.jpg",
  "lenador-polea": "/images/ejercicios/db/lenador-polea.jpg",
  "molino-kettlebell": "/images/ejercicios/db/molino-kettlebell.jpg",
  "mountain-climbers": "/images/ejercicios/db/mountain-climbers.jpg",
  "muscle-up-barra": "/images/ejercicios/db/muscle-up-barra.jpg",
  "oruga": "/images/ejercicios/db/oruga.jpg",
  "pajaros-mancuernas": "/images/ejercicios/db/pajaros-mancuernas.jpg",
  "pallof-press": "/images/ejercicios/db/pallof-press.jpg",
  "patada-triceps": "/images/ejercicios/db/patada-triceps.jpg",
  "peso-muerto": "/images/ejercicios/db/peso-muerto.jpg",
  "peso-muerto-rumano": "/images/ejercicios/db/peso-muerto-rumano.jpg",
  "peso-muerto-sumo": "/images/ejercicios/db/peso-muerto-sumo.jpg",
  "plancha": "/images/ejercicios/db/plancha.jpg",
  "plancha-lateral": "/images/ejercicios/db/plancha-lateral.jpg",
  "prensa-piernas": "/images/ejercicios/db/prensa-piernas.jpg",
  "press-arnold": "/images/ejercicios/db/press-arnold.jpg",
  "press-banca": "/images/ejercicios/db/press-banca.jpg",
  "press-banca-mancuernas": "/images/ejercicios/db/press-banca-mancuernas.jpg",
  "press-banca-multipower": "/images/ejercicios/db/press-banca-multipower.jpg",
  "press-cerrado-banca": "/images/ejercicios/db/press-cerrado-banca.jpg",
  "press-declinado-barra": "/images/ejercicios/db/press-declinado-barra.jpg",
  "press-frances": "/images/ejercicios/db/press-frances.jpg",
  "press-hombros-maquina": "/images/ejercicios/db/press-hombros-maquina.jpg",
  "press-inclinado-barra": "/images/ejercicios/db/press-inclinado-barra.jpg",
  "press-inclinado-mancuernas": "/images/ejercicios/db/press-inclinado-mancuernas.jpg",
  "press-mancuernas-de-pie": "/images/ejercicios/db/press-mancuernas-de-pie.jpg",
  "press-mancuernas-hombros": "/images/ejercicios/db/press-mancuernas-hombros.jpg",
  "press-maquina-pecho": "/images/ejercicios/db/press-maquina-pecho.jpg",
  "press-militar": "/images/ejercicios/db/press-militar.jpg",
  "press-suelo-mancuernas": "/images/ejercicios/db/press-suelo-mancuernas.jpg",
  "press-vertical": "/images/ejercicios/db/press-vertical.jpg",
  "puente-gluteo": "/images/ejercicios/db/puente-gluteo.jpg",
  "puente-gluteo-unilateral": "/images/ejercicios/db/puente-gluteo-unilateral.jpg",
  "pullover-polea": "/images/ejercicios/db/pullover-polea.jpg",
  "push-press": "/images/ejercicios/db/push-press.jpg",
  "remo-barra": "/images/ejercicios/db/remo-barra.jpg",
  "remo-invertido": "/images/ejercicios/db/remo-invertido.jpg",
  "remo-mancuerna": "/images/ejercicios/db/remo-mancuerna.jpg",
  "remo-menton": "/images/ejercicios/db/remo-menton.jpg",
  "remo-polea-baja": "/images/ejercicios/db/remo-polea-baja.jpg",
  "remo-renegado": "/images/ejercicios/db/remo-renegado.jpg",
  "rotaciones-landmine": "/images/ejercicios/db/rotaciones-landmine.jpg",
  "rueda-abdominal": "/images/ejercicios/db/rueda-abdominal.jpg",
  "russian-twist": "/images/ejercicios/db/russian-twist.jpg",
  "salto-al-cajon": "/images/ejercicios/db/salto-al-cajon.jpg",
  "salto-horizontal": "/images/ejercicios/db/salto-horizontal.jpg",
  "sentadilla-barra": "/images/ejercicios/db/sentadilla-barra.jpg",
  "sentadilla-con-salto": "/images/ejercicios/db/sentadilla-con-salto.jpg",
  "sentadilla-frontal": "/images/ejercicios/db/sentadilla-frontal.jpg",
  "sentadilla-goblet": "/images/ejercicios/db/sentadilla-goblet.jpg",
  "sentadilla-hack": "/images/ejercicios/db/sentadilla-hack.jpg",
  "sentadilla-multipower": "/images/ejercicios/db/sentadilla-multipower.jpg",
  "sit-up": "/images/ejercicios/db/sit-up.jpg",
  "snatch-kettlebell": "/images/ejercicios/db/snatch-kettlebell.jpg",
  "step-up": "/images/ejercicios/db/step-up.jpg",
  "superman": "/images/ejercicios/db/superman.jpg",
  "swing-kettlebell": "/images/ejercicios/db/swing-kettlebell.jpg",
  "thruster": "/images/ejercicios/db/thruster.jpg",
  "tijeras-verticales": "/images/ejercicios/db/tijeras-verticales.jpg",
  "turkish-get-up": "/images/ejercicios/db/turkish-get-up.jpg",
  "zancada-trasera": "/images/ejercicios/db/zancada-trasera.jpg",
  "zancadas-caminando": "/images/ejercicios/db/zancadas-caminando.jpg",
  "zancadas-mancuernas": "/images/ejercicios/db/zancadas-mancuernas.jpg",
};

export function exerciseImage(id: string): string | undefined {
  return EXERCISE_IMAGES[id];
}
